-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
INNER JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = 2022 AND MONTH(BS.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

# SELECT  A.AUTHOR_ID, 
#         A.AUTHOR_NAME,
#         B.CATEGORY,
#         SUM(SALES * PRICE) AS TOTAL_SALES
# FROM BOOK_SALES BS
# JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID
# JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
# WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
# GROUP BY A.AUTHOR_ID, B.CATEGORY
# ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;


# WITH BTS AS (
# SELECT BB.BOOK_ID, BB.AUTHOR_ID, BB.CATEGORY, SUM(BSS.SALES), BB.PRICE * SUM(BSS.SALES) AS TOTAL_SALES
# FROM BOOK AS BB
# INNER JOIN BOOK_SALES AS BSS ON BB.BOOK_ID = BSS.BOOK_ID
# GROUP BY BB.BOOK_ID, BB.CATEGORY
# )
# SELECT *
# FROM AUTHOR AS A
# INNER JOIN BTS ON BTS.AUTHOR_ID = A.AUTHOR_ID



