-- 코드를 입력하세요


SELECT YEAR(b.SALES_DATE) AS YEAR, MONTH(b.SALES_DATE) AS MONTH, a.GENDER AS GENDER, count(DISTINCT a.USER_ID )AS USER
FROM USER_INFO a JOIN ONLINE_SALE b
ON a.USER_ID = b.USER_ID
WHERE a.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER

# # SELECT COUNT(OS.SALES_DATE) AS MONTH
# # FROM USER_INFO AS UI
# # INNER JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
# # GROUP BY MONTH(OS.SALES_DATE)

# # SELECT COUNT(UI.GENDER) AS GENDER
# # FROM USER_INFO AS UI
# # INNER JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
# # GROUP BY GENDER

# SELECT COUNT(UI.USER_ID) AS USERS
# FROM USER_INFO AS UI
# INNER JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
# GROUP BY OS.USER_ID